# Database Connection Monitor Configuration
spring:
  application:
    name: db-connection-monitor
  

# Database monitoring configuration
db:
  monitor:
    enabled: true
    # Health check query to execute
    health-check-query: "SELECT 1"
    # Connection timeout in milliseconds
    connection-timeout: 5000
    # Maximum consecutive failures before shutdown
    max-failure-threshold: 3
    # Critical pool utilization threshold (0.0 to 1.0)
    critical-pool-utilization: 0.9
    # Critical number of threads waiting for connections
    critical-waiting-threads: 10
    # Monitoring interval in milliseconds (30 seconds)
    monitoring-interval: 30000





