# Database Connection Monitor Configuration
spring:
  application:
    name: db-connection-monitor

# Database monitoring configuration
db:
  monitor:
    enabled: true
    # Health check query to execute
    health-check-query: "SELECT 1"
    # Maximum consecutive failures before considering shutdown
    max-failure-threshold: 3
    # Critical pool utilization threshold (0.0 to 1.0) - for logging only
    critical-pool-utilization: 0.9
    # Monitoring interval in milliseconds (30 seconds)
    monitoring-interval: 30000

# Logging configuration
logging:
  level:
    com.zaxxer.hikari: WARN





